### ISSUE TITLE
Pomoc przy testach

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker-PTR#1]
Potrzebujecie mieć te rzeczy przetestowane. Niestety 3/6 punktów z readme nie da się wykonać samemu, a zebranie ludzi na PTR na raid/rdf, a tym bardziej bg graniczy z cudem. Dajcie opcję na god mode i/lub kill.

Bez tego rdf nie będzie sprawdzone, master loot, wejścia do instancji itp bo po prostu nie będzie ludzi

**Comment by Malylolek** [comment]
Cieżko jest zebrać skoro PTR jest zamkniety znowu :P 

Spite - wystarczy napisać masz gildie która chętnie potestuje jak sie ja zawoła.

**Comment by Varchord** [comment]
Ta juz to widzę. Jak ptr na 434 stal to pytałem wiele razy. Wszyscy mówili ze pomogą, a jak przychodzilo co do czego to w dupie mieli i nie chciało im sie na ptr wchodzic

**Comment by Malylolek** [comment]
No jakoś gdy testowaliśmy ciebie nie było wiec gdzie problem :P
