### ISSUE TITLE
[EN/PL][Raid-Cata]Firelands

### ISSUE THREAD

**Issue by mitim1** [Atlantiss/BugTracker-PTR#2]
Beth'tilac
-Spinnery powinny przestać się spawnic jeśli ktos jest na sieci
-Spiderlingi są immune na slowy.
-Pająki nie znikają po zabiciu bossa.
-Pety wchodzą na siec i bija bossa.
-Trigery są widoczne.
-Spinnery wchodzą na siec i bija mele.
-Meteor nie zostawia dziury w sieci. (Wcześniej działało)
-Na 2 fazie boss dostaje The Widow’s Kiss zamiast jego obecnego targetu.
-Na 2 fazie boss ma immune na fire.
-Jeśli Spinnery nie zostały zbite następna ich fala pojawi się w tym samym miejscu. 
-Bethilac have incorrect HP value (20,6 M HP on 10 nm when should have 20,816,178 HP)
-There should be only 2 Cinderweb Spinner per wave on 10 man normal
-Cinderweb Spinner have incorrect Hp value (278,5k HP on 10 nm when should have 232.5 k HP) - probably same issue with Drone/Spiderlings/Broodling
-Cinderweb Spinner powinny używać Burning Acid co 2 sekundy.

Shannox
-The freezing trap effect (npc) is not rooted on the trapped player/npc so it moves around sometimes
-Freezing traps range is bit too high
-Rageface can be taunted
-Shannox also despawns after a crash.
-Face Rage powinien być przerywany jeśli Rageface dostanie 30k+ dmg z 1 hita.
-Na Rageface zostaje buff z FaceRage nawet jeśli go nie castuje 
-Brama do Balerocka powinna się otwierać w monecie pojawienia się Shannoxa

Alysrazor
-Kiedy boss jest w wulkanie można go pulnac petem.
-Trigery są widoczne
-Ma 88lvl a powinien mieć lvl boss
-Lave Spew bije na nieskończoną wysokość
-Stojąc bezpośrednio na Plump Lava Worm nie dostajemy dmg z Lava Spew
-Blazing Talon Initiate się poruszają i latają (Powinny być zrutowane w 1 miejscu) 
-Na Blazing Talon Initiate działa każde cc oraz powinny być max 2 na raz
-Blazing Power można targetować i zabić, czasem spawnia się poprawie a czasem są mniejsze z trigerem w srodku
-Blazing Claw nie działa
-Voracious Hatchling maja za 196 hp

Lord Rhyolith
- Rhyolith should pull when you reach certain range (see on retail movie)
- Foots should be targetable before the pull
- Few triggers are visible
- Sometimes after wipe Rhyolith spawns where he was when raid wiped ex. in Lava
- There is platform on ATS but it should disappear after boss pull and after wipe/kill/reset it should appear (see on retail movie)
- Rhyolith's trying to Ignite everything not only volcano which cause beam on every payer/mob/trigger (see on ATS movie)
- Ignited Volcono don't deal damage to player (prawdopodobnie po podpaleniu które leci na wszystkich sam wulkan nie zostaje podpalony o czym może świadczyć inny niż na ATS model podpalonego wulkanu na retailu widać to na obu filmikach)
- Steering Rhyolith is also bugged the "direction gauge" is always at 50% which causes Rhyolith to move forward here is how it should work:

The value indicated/displayed by the bar shows where Rhyolith is currently steering:
the closer to the left (or 0%), the more Rhyolith is steering left;
the median value (or 50%) represents Rhyolith moving in a straight line;
the closer to the right (or 100%), the more Rhyolith is steering right.

- Dealing dmg to L / R foot sometimes changes direction of his movement sometimes it's not but bar is always unchanged at 50%

Baleroc
Crashuje server (testowane 06.05 kolo 10 i boss znów crashował)

Majordomo
-Leaping Flames nie znikaja po wipe
-Spirit of the Flame pojawiają się za szybko.
-Jeśli boss raz wejdzie w forme elfa już nie wchodzi w inne formy.
-Searing Seeds nie dzialaja
-
Ragnaros
-Trigery biegają i mija z mele 
-Respi się trochę za wysoko
-Magma trap nie działa, plama pojawia się w randomowy miejscu a nie na pozycji jakiegoś gracza 
-Sulfuras Smash nie zawsze idzie tam gdzie był jego marker/nie widać markera 
-Boss nie używa Magma Blast
-Boss nie używa Wrath of Ragnaros
-Meteor powinien mieć 126 mln hp
-Meteor switchuje target co 2-3 sekundy.
-Cc dziala na Meteora
-Meteor powinien mieć aure Combustible 
-Lava Bolt nie działa 
-Engulfing falme działa, ale bardzo często jest przy mele a nie w losowym miejscu 
-Blazing Heat nie leczy Scionów 
-Blazing Heat dział bardzo nie regularnie i debuff jest za krotki . 

Thrash and NPC's:
- missing event with Kar before Rhyolith (you can se on movie how it should work)
- missing event that summons Alysrazor
- every thrash mob stands in one place when they should patrol the inscance (from what I know Savek scripted most of them so probably they're not implemented)
- missing NPC's inside instance SS where they should stand: http://i.imgur.com/HwYtcoC.jpg 
- missing NPC's and Meeting Stone at entrance to Firelands SS where they should stand: http://i.imgur.com/GMnaj2I.jpg

Links: 
http://www.wowhead.com/npc=54401/naresir-stormfury 
http://www.wowhead.com/npc=54402/lurah-wrathvine http://www.wowhead.com/npc=52672/flameward-hippogryph

Lord Rhyolith
Retail : https://www.youtube.com/watch?v=yWXrpVwUJ4Q
ATS : https://www.youtube.com/watch?v=CNvwXeloRTE

Missing event with Kar
https://www.youtube.com/watch?v=2GlyTZlJk5g

**Comment by Jenovas** [comment]
Boss nie castuje Meteor Burn - castuje tylko na osoby które mają debuffa od pajęczyny.

**Comment by mitim1** [comment]
Nie, podczas walki nie wycastowal nawet 1.
Filmik z walki z Beth'tilac
https://www.youtube.com/watch?v=q-KNGuxTPWY&feature=youtu.be

**Comment by Varchord** [comment]
Ugluk możesz zamknąć. Zformatowana wersja
https://github.com/Atlantiss/BugTracker-PTR/issues/7
