### ISSUE TITLE
[EN] Gearing on the PTR

### ISSUE THREAD

**Issue by ahtebe** [Atlantiss/BugTracker-PTR#26]
Valor and conquest points are limited to their normal cap. Completing the quest to earn more does nothing.
This means valor point items can't be bought.

I heard the .gangnamstyle was supposed to give gear or something, but it doesn't do anything it just appears on the chat bubble.

I wanted to test out some classes spells with different gear levels (346 to 359 to 372), but I found this to be impossible.

**Comment by Varchord** [comment]
It's not a bug

**Comment by ahtebe** [comment]
So we are supposed to get only Head and Shoulders from valor and the rest with justice?

**Comment by Varchord** [comment]
I'm saying it's not a bug. Besides. Nothing changes with spells. the only thing present on PTR which is not on main realm is Firelands

**Comment by ahtebe** [comment]
You made yourself clear in your first message. In my second message I made a very simple question: So we are supposed to get only Head and Shoulders from valor and the rest with justice?

I'll close this then.
