### ISSUE TITLE
[PL][Raid-Cata] Firelands

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker-PTR#7]
# [Beth'tilac 25](http://www.wowhead.com/npc=52498/bethtilac)
* [Ember Flare](http://www.wowhead.com/spell=98934/ember-flare) bije za malo(cokolwiek to znaczy)

# [Shannox 25](http://www.wowhead.com/npc=53691/shannox)
* ...

# [Alysrazor 25](http://www.wowhead.com/npc=52530/alysrazor)
* HP po nefach
  * 10    *38,651,400*
  * 10H    *65,707,380*
  * 25    *115,954,200*
  * 25H    *197,122,144*
* HP przed nerfami
   * 10 man/norm *51 535 200*
   * 10H *77 302 800*
   * 25 *154 605 600*
   * 25H *231 908 404*
* Ma za mały hitbox na 4 fazie
* Wszystkie addy mają za mało HP
 * [Blazing Talon Initiate](http://www.wowhead.com/npc=53611/blazing-talon-initiate)
    * 10    *320,780*
    * 10H    *801,950*
    * 25      *962,340*
    * 25H   *2,405,850* 
 * [Voracious Hatchling](http://www.wowhead.com/npc=53898/voracious-hatchling)
    * 10    *13,942,992*
    * 10H    *6,349,041*
    * 25      *22,076,404*
    * 25H    *9,170,837*
* Debuff [Hungry](http://www.wowhead.com/spell=99361/hungry) nie wchodzi

# [Lord Rhyolith 25](http://www.wowhead.com/npc=52558/lord-rhyolith)
* Wartosci HP po nerfach
  * *10    13,113,000*
  * 10H    *19,927,178*
  * 25    *39,939,780*
  * 25H    *7,100,000*
* Wartosci przed nerfami
 * 10 *15 427 058*
 * 10H *23 443 738*
 * 25 *46 987 976*
 * 25H *70,00 M (L/R Foot 35,00 M)*
* [Fragment of Rhyolith](http://www.wowhead.com/npc=52620/fragment-of-rhyolith)
  * Po nerfach
    * 10    *135,608*
    * 10H    *197,600*
    * 25   *387,450*
    * 25H    *650,916*
 * Przed nerfami
    * 10  *155 k*
    * 10H  *232,5 k*
    * 25  *464,9 k* 
    * 25H *767,2 k*
* [Spark of Rhyolith](http://www.wowhead.com/npc=53211/spark-of-rhyolith)
  * Po nerfach 
     * 10      *1,449,064*
     * 10H    *2,169,721*
     * 25      *4,726,891*
     * 25H    *7,051,591*
  * Przed nerfami
    * 10  *1.70 M*
    * 10H  *2,6 M *
    * 25  *5,6 M *
    * 25H   *8,37 M *
* [Liquid Obsidian](http://www.wowhead.com/npc=52619/liquid-obsidian)
 * 10H *294,5 k*
 * 25H *533,9 k*
* Filmiki
 * [Retail](https://www.youtube.com/watch?v=yWXrpVwUJ4Q)
 * [Atlantiss](https://www.youtube.com/watch?v=CNvwXeloRTE)
 
# [Baleroc 25](http://www.wowhead.com/npc=53494/baleroc)
 * Powinien zwiększać [Savage Defense](http://cata.openwow.com/spell=62606)
  * [Opis debuffa](http://i.imgur.com/UXuB7uK.jpg)

# [Majordomo Staghelm](http://www.wowhead.com/npc=52571/majordomo-staghelm)
* ...

# [Ragnaros](http://www.wowhead.com/npc=52409/ragnaros#abilities)
 * [Sulfuras Smash](http://www.wowhead.com/spell=98710/sulfuras-smash) wybiera sobie jeden target i kurczywie się go trzyma. Nawet po wipe
* [Lava Bolt](http://www.wowhead.com/spell=98981/lava-bolt) na 25 leci w 25 targetów, powinien w 10. Czasem lecą 2 w jeden target

# Trash
* Brak Eventu przed [Lord Rhyolith](http://www.wowhead.com/npc=52558/lord-rhyolith)
 * https://www.youtube.com/watch?v=2GlyTZlJk5g
* Trash ma za mały melee dmg

# Other 
* Repa [Avengers of Hyjal](http://www.wowhead.com/faction=1204/avengers-of-hyjal) nie leci z trashu/bossów 
* NPC przed instą powinny siedzieć na gryfach, zamaist stać obok nich
 * [Screen](https://camo.githubusercontent.com/bfd4c1a87ae9fdc194520c007412ae5092877b78/687474703a2f2f7a61706f64616a2e6e65742f696d616765732f333139633334643035316530622e6a7067)

# [Wszystkie wartosci HP Fireland Pre-nerf](http://community.atlantiss.eu/index.php?/topic/4551-enpl-firelands-testing-development-realm/)

**Comment by Varchord** [comment]
Nie polska część serwera ma wywalone na PTR więc nie tłumacze na angielski. Nie ma to sensu, a sądze, że devom wygodniej tak będzie

**Comment by aneq** [comment]
dodaj jeszcze, że poza błędnym spawnowaniem się magma trapów, nie działają one

**Comment by Varchord** [comment]
Ej a nie bylo czasem problemow z pullaniem Majordomo Staghelma?

**Comment by Jenovas** [comment]
Cinderweb Spinner
1. Powinny przestać się spawnic jeśli ktos jest na sieci
Oglądnąłem własnie filmik jak retri Palek na 6.0.2 soluje tego bossa i mimo iż był na sieci to pająki dalej wychodziły.z tego co widzę to jest 2-3 fale co 10 sekund a potem długa przerwa i po Devastate znów 2-3 fale niezależnie czy jest ktoś nie sieci czy nie.

2. Powinny się spawnić w 10s odstępach
Z tego samego filmiku wydawało mi się że to jest między 10 a 12 sekund, bo raz wyszły 10 sekund równo a potem wydawało mi się że było bliżej 11 sekund.

3. Meteor Burn nie zostawia dziury w sieci. (Wcześniej działało) i  Burning Acid powinno być castowane co 2 sekundy. 
Powinno zacząć działać z next upem PTRa, dam Wam znać kiedy to nastąpi.

4. The Widow’s Kiss rzuca na siebie zamiast na obecny target i Na 2 fazie boss ma immune na fire są powiązane. Z tego co widzę to Widow's Kiss daje immune na fire damage.

**Comment by Varchord** [comment]
Wykreślone to co zupdatowane. Jesli działa to usunę całkowicie

**Comment by Varchord** [comment]
Ja widze, ze Salg cos z Rhyolitha naprawil. wypowiedzialby sie tu a nie :P

**Comment by aneq** [comment]
ja tam widze ze fix savka

**Comment by Varchord** [comment]
No  kurde faktycznie. Zobaczyłem 's' i się podekscytowałem, żę salgu xd

No to Savek by się mógł wypowiedzieć ^^

**Comment by Savek** [comment]
Źle commit opisalem, tak fixy tylko do Rhyolitha

**Comment by Varchord** [comment]
Na razie wykreślone, po sprawdzeniu usunę

**Comment by Quban** [comment]
Pare fixow do FL http://atlantiss.eu/changelog#rev4460

**Comment by Varchord** [comment]
Gado lami!

Co Ty mnie tu pokazujesz nie wrzucone fixy, Aż mi smutno

**Comment by Varchord** [comment]
Alysrazor UPDATED

**Comment by Savek** [comment]
Blazing Claw nie działa 

Jak ostatnio sprawdzalem dzialalo. I jak możecie wypiszcie all moby, które maja mieć jakiś immune, to szybko sie poprawi.

**Comment by Varchord** [comment]
Savek to wyglądało tak, jakby część fixów z tych samych commitów działało/było wrzuconych, a część nie

**Comment by Quban** [comment]
"Circle of Thorns portale nie działają" pytanie: Zabiliscie wszystkie 5 bossow?

**Comment by Varchord** [comment]
Wszsytkie 5 bossow. Knufel anwet instancje zresetowal, przelecial sie zajebal wszytko i nadal kupa. 
A czytales co sie dzieje z tym mostem twoim? ^^

**Comment by Quban** [comment]
Tam jest sciana niewidzialna zapomnialem o tym

**Comment by Quban** [comment]
Zapomnialem w logu wpisac, ze npc przed insta juz po 1 sztuce powinny byc

**Comment by Varchord** [comment]
Salgu zajalbys sie rzeczami istotnymi takimi jak https://github.com/Atlantiss/BugTracker/issues/444 a nie warlockom pety naprawial. Kazdy ma lockow w  dupie, ty tez powinienes xD

**Comment by Malylolek** [comment]
To jest quban noob z ally .... spite no plis

W dniu piątek, 12 czerwca 2015 Varchord <notifications@github.com>
napisał(a):

**Comment by Quban** [comment]
Przeciez ja jeszcze aż tak dobry nie jestem, żeby mnie za salga brać ;p

**Comment by Varchord** [comment]
Kurwa to jaki salgu mial nick. myslalem ze ten xd

**Comment by Malylolek** [comment]
salg z epitetami  " Salgarksiu
<http://atlantiss.eu/armory/character/121968#view-page> "

**Comment by Varchord** [comment]
Dobra dobra 
Stesknilem sie za salgiem i wyobrazalem sobie, ze to on :<

**Comment by mitim1** [comment]
Bethilac
Meteor trigeruje się wizulanie na ziemi.
Boss jest immune na taunta na 2 fazie.
Triger na pajęczynie jest widoczny.
Pety i moby nadal wchodzą na sieć
W czasie 2 fazy jest dronowi kończy się energia idzie on na siec i dostaje energie.

Alyslazor
Suitiated i Hangry naraz.

Majordomo
Thrash nie jest odporny na cc 
5 Bossow na sobie 
Przy każdej zmianie formy wraca pod schody.

**Comment by InformatorPE** [comment]
http://zapodaj.net/9815a2b369b6d.jpg.html
Ten Burning Orb powinien być tak za pagórkiem?
(https://www.youtube.com/watch?v=FH3ZJqSToMA)

**Comment by Varchord** [comment]
Pogadam w najblizym czasie z uglikiem/aneqiem co tam jest do dopisania i dodam

**Comment by Quban** [comment]
co jest nie tak z lava spew i fireroblastem? ze niby dmg sie nie zgadza?

**Comment by mitim1** [comment]
Bethilac
Gdy main target bossa spadnie z sieci boss nie zmienia swojego na osobę będąca na sieci.
Gdy osoba na której boss ma target spadnie na dól boss na parę sekund skacze za nim.
Po ostatniej poprawce Drony wgl nie wchodzą na siec aby zaczerpnąć energie od bossa (nawet na 1 fazie)

Alyslazor
Blazing Claw jest buffem a powinien debuffem
Blazing Talon Clawshper spawnia się za daleko od bossa
W 3 fazie po 5 sekundach powinno usunąć ludziom skrzydła
Blazing Talon Initiate biją z mele i obracaj się w kierunku swojego targetu.
Boss randomow znika (gmowi nie znikną wiec prawdopodobnie jest to związane ze zimna faz)
W 4 fazie boss ma animacje latania zamiast chodzenia
Debuff imprinted działa strasznie randomowo
Gushing Wound prawdopodobnie bije za malo
Prawdopodobnie jest kilka tornad w 1 miejscu na 2 fazie

**Comment by Varchord** [comment]
Ugluk jutro po Sinestrze usiądziemy i to uzupełnimy. Nie miałem jak dziś być, przed godziną wróciłem :P

**Comment by mitim1** [comment]
kk

**Comment by Varchord** [comment]
Dobra, zapomniało się wczoraj. Uzupełnaim sam :P

**Comment by Varchord** [comment]
UPDATED Alysrazor
UPDATED Bethilac
UPDATED Majordomo


Nie biorę za to odpowiedzialności bo mnie nie było. Dodałem tylko Ugluka posty bo mam do niego zaufanie że nie spierdolił ^^

**Comment by Varchord** [comment]
UPDATE Bridge Invisible Wall
UPDATE Portals

**Comment by mitim1** [comment]
Npc przed/w Firelands
http://zapodaj.net/319c34d051e0b.jpg.html
http://zapodaj.net/051297bd0e346.jpg.html
http://zapodaj.net/6c7d8ed2ed087.jpg.html
http://zapodaj.net/beadedc03b004.jpg.html

**Comment by Varchord** [comment]
Hehe, Ugluk ma rogala?

**Comment by aneq** [comment]
to postać knufla z ptra/main realmu z globa,
masz nawet tam w quest logu questy z woda
a ty nie spamuj tylko lepiej dodaj do shannoxa ze aura Wary dajaca psom immune na trapy ktora pies dostaje po zejsciu trapa trwa 15 sekund zamiast 30

**Comment by Varchord** [comment]
Nic nie dodaje, foch i chuj. Sprzeciw i strajk za bana na forum

**Comment by Varchord** [comment]
UPDATED Other
UPDATED Bethilac
UPDATED Ryolith
UPDATED Shannox

**Comment by PierwszyKrytykRP** [comment]
Zupdatowałem co tam pamiętałem/wiedziałem, dodałem, usunąłem.
Wrócę z roboty to może to z anqiem jak człowiek zrobimy

**Comment by Asavel** [comment]
Dodaj do shanoxxa ze dmg nie zawsze przerywa channel psa

**Comment by PierwszyKrytykRP** [comment]
Depsic nie umiecie, a nie ze nie dziala

**Comment by PierwszyKrytykRP** [comment]
UPDATE wszystkiego byl

**Comment by mitim1** [comment]
Leaping Flames
Skacze w melasów -Usuń

**Comment by mitim1** [comment]
Można tauntować meteory-Usuń

**Comment by mitim1** [comment]
Living Meteor
Podatny na CC-Usuń

**Comment by mitim1** [comment]
NPC nie patrolują instancji-Usuń

**Comment by PierwszyKrytykRP** [comment]
UPDATE!

**Comment by PierwszyKrytykRP** [comment]
UPDATE HP o malo kurwicy nie dostalem, a github ma chujowe spoilertagi

**Comment by xolon** [comment]
https://www.youtube.com/watch?v=7A-WKaifkIg&feature=youtu.be
Beth from last night, i don't wanna write any bug report cause these bugs are maybe reported already, see if you find something new

**Comment by aneq** [comment]
Well as far as I know Beth'tilac sometimes bugs out when someone fails on the web (but that will be fixed when mmaps will be introduced to firelands), smoldering devastation doesn't repair the holes in the web (but savek said he fixed that already) aaand aoe damage seems too low in p2 but that might just be overnerfed boss.

**Comment by Frainzil** [comment]
dmg might be ok, BUT on retail video's the aoe dmg happens every 7 seconds. For us the aoe dmg was every 15seconds. So it should be twice as often.

**Comment by mitim1** [comment]
Spajcik, Usuń z Betilaca wszystko i daj że "Ember Flare" (linki później znajdę)
Shanaoxa całego Usuń
Na Alysrazorze zostaw Hp,hitbox i "hungry" reszte usuń
Z Beleroca zostaw  tylko "Powinien zwiększać Savage Defense" reszte usuń
Majodomo usuń wszyskto
Ragnaros usuń to co tam jest i dodaj ze "Sulfuras Smash" wybiera jeden target i się go trzma nawet po wipe.
Do ragnaros dodaj jeszcze ze na 25 "Lava Bolt" lecą w 25 targetow (powinny w 10) i ze czasami lecą 2 w jedna osobe

**Comment by PierwszyKrytykRP** [comment]
UPDATED 22.12.2015 rev 4729(chyba)

Ehh, co ja się z wami mam. 

25k EP za update zgłoszenia

**Comment by Quban** [comment]
repa pewnie nie wgrana ale sql bylo :D

**Comment by Quban** [comment]
jesli loot zle dropi tzn ze nie wgrane bylo

**Comment by PierwszyKrytykRP** [comment]
A repa gildijna to juz naprawiona jest?

**Comment by mitim1** [comment]
Edit
