### ISSUE TITLE
[EN][Spell] Teleport: x crashes

### ISSUE THREAD

**Issue by Atraac** [Atlantiss/BugTracker-PTR#8]
Using most Mages Teleport: spells crashes the server. So far I see that only Orgimmar doesn't cause a crash. Heartstones, portals etc. work just fine.

Current PTR rev: 4454

**Comment by Varchord** [comment]
A gdzie [EN]? Do zamknięcia, błędne zgłoszenie, atrak nup

**Comment by Varchord** [comment]
I just want to say that "Teleport: Moonglade" and Deathgate is working fine

**Comment by Atraac** [comment]
Not anymore.
